/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e68a5ee8-5387-463c-a3f7-f65142d18aa4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Iht6rnGlO",
    "aws_user_pools_web_client_id": "41h9uvqrq8ighn9lfh7shln0t9",
    "oauth": {}
};


export default awsmobile;
